steps:

# Trigger unit tests for the backend. Turned off for unblocking the release.
# - id: backend_unit_tests
#  name: 'gcr.io/cloud-builders/mvn'
#  args: ['clean', 'test']
#  dir: "backend"

# Trigger coverage tests for the backend. Turned off for unblocking the release.
# - id: backend_coverage_report
#  name: 'gcr.io/cloud-builders/mvn'
#  args: ['jacoco:report']
#  dir: "backend"

# Prepare frontend environment for unit testing.
- id: 'frontend_install_dependencies'
  name: 'buildkite/puppeteer'
  args: ['npm', 'install']
  dir: "frontend/rolecall"

# Trigger unit tests for the front.
- id: frontend_unit_tests
  name: 'buildkite/puppeteer'
  args: ['npm', 'run', 'test']
  dir: "frontend/rolecall"

# Trigger unit tests with coverage for the front.
# - id: frontend_coverage_report
#   name: 'buildkite/puppeteer'
#   args: ['npm', 'run', 'coverage']
#   dir: "frontend/rolecall"
